---
title: "DREAM5"
author: "Adriano Martinelli"
date: "27/04/2018"
output: html_document
---

#Install package
```{r}
rm(list = ls())
# source("http://www.bioconductor.org/biocLite.R")
# biocLite("limma")
# biocLite("nem")
# install.packages("ggplot2")
# install.packages("pheatmap")
# install.packages("tidyverse")
# biocLite("statmod")


```

#Load libraries
```{r}
library(nem)
library(readr)
library(DESeq2)
library('dplyr')
library('tidyr')
library(ggplot2)
library(knitr)
library(abind)
```

#Parameter
```{r}
#Either set network to default or read argument given to script
args = commandArgs(trailingOnly = TRUE)
args = as.numeric(args)

if(length(args) == 0){
  network = c(3)
}else if(length(args) == 3){
  network = args[1]
}else if(length(args) == 1){
  network = args[1]
}

#Working directory
wd = "/Users/adrianomartinelli/polybox/ETH/Bachelor\ Thesis/DREAM\ Challange/DREAM5/DREAM5_network_inference_challenge/Evaluation\ scripts/NEM\ Script/"

#Euler
#wd = "/cluster/home/adrianom/DREAM5_EULER/Evaluation scripts/NEM Script"

#Folder
path = "../../"
folder = paste0("Network", network,"/")

#Path to save objects
file_out = paste0(path, folder)

#Inference methods
method = c("pval", "odds")

ADJUST = F
THRESHOLD = T

#Appendix for adjustement
adj = "";
if(ADJUST == TRUE) adj = "_adjusted"

thr = "";
if(THRESHOLD == TRUE) thr = "_threshold"


######################################################################################################
######################################################################################################
```

#Read in Files
```{r}
setwd(wd)

#load functions
source("DREAMFUN.R")

#load workspace
load(paste0(path, folder, "net", network,"_NEM", adj, ".RData"))
######################################################################################################
######################################################################################################
```

#Write files with edges
```{r}

#hyper = set.default.parameters(colnames(pdensity))
#hypertype = "CONTmLLBayes"
#hyper$type = hypertype

#Write sorted list of edges to dir
data = list(bs_Bayes_pval, bs_Bayes_odds)
countNEM = data_frame(countRnd = -1, countNull = -1)

  for(j in 1:length(data)){
  setwd(wd)
  setwd(paste0(path, folder, "Predictions/", method[j]))
    
  graph = data[[j]]
  
  tmpcount = 1
  
  for(i in thresholds){

    #apply threshold on s-nodes
    g = (graph >= i) * 1
    
    #Transitively close network
    #MODIFY:
    g = transitive.closure(g, mat = T ,loops = F)
    
    #Convert to list of edges
    Spred = gather(as.data.frame(g), N2, Edge)
    Spred = cbind(rownames(g), Spred)
    colnames(Spred) = c("N1", "N2", "Edge")
    
    #Remove self regulation
    idx = which(Spred$N1 == Spred$N2)
    Spred = Spred[-idx,]
    
    #Find Egenes attachments
    res = nem(pdensity, models = g, inference = "search", control = hyper)
    res$pos = res$pos[[1]]
    res$mappos = res$mappos[[1]]
    res$mLL = res$mLL[[1]]
    res$LLperGene = res$LLperGene[[1]]
    res$para = res$para[[1]]
    res$control = res$control[[1]]
    
    #Variable to manipulate res$pos
    res.pos = res$pos
    
    #Find indices of Snodes in res$pos
    idx = lapply(KOgenes, function(x) which(rownames(res.pos) == x))
    
    #Remove Snodes from Egenes list
    if(length(unlist(idx)) != 0) res.pos = res.pos[-unlist(idx), ]
    
    
    # #Select for each Egenes: Snode with highest probability, if necessary randomly
    # countRnd = 0
    # countNull = 0
    # for(n in 1:dim(res.pos)[1]){
    #   tmp = which(res.pos[n,] == max(res.pos[n,]))
    #   if(length(tmp) > 1){
    #     countRnd = countRnd + 1
    #     if(max(tmp) == ncol(res.pos)){
    #     tmp = ncol(res.pos)
    #     countNull = countNull + 1
    #     }else{
    #     tmp = sample(tmp, 1)
    #     }
    #   }
    #   res.pos[n,-tmp] = 0
    # }
    
    #Store stats 
    #countNEM[tmpcount, ] = c(countRnd, countNull)
    #tmpcount = tmpcount + 1
    
    #Remove null node
    res.pos = res.pos[,1:(length(KOgenes))]
    
    #Apply threshold on res.pos
    if(THRESHOLD == TRUE){
      res.pos = (res.pos >= i) * 1
      }else if(THRESHOLD == F){
      res.pos = (res.pos > 0) * 1
      }
    
    #transpose of res.pos to get directed edges
    res.pos = t(res.pos)
    
    Epred = gather(as.data.frame(res.pos), N2, Edge)
    Epred = cbind(rownames(res.pos), Epred)
    colnames(Epred) = c("N1", "N2", "Edge")
    Epred = rbind(Spred, Epred)

    write_tsv(Epred, paste0("net", network, adj, thr,"_List_of_Edges_", method[j], "_", i, "_.tsv"), col_names = FALSE)
  }
  print(paste0("Warnings: ",warnings()))
  print(paste0("Finished: Thresholds ",method[j]))
}

######################################################################################################
######################################################################################################
print(paste0("Warnings: ",warnings()))
print(paste0("Finished: Prediciton network ", network))
```





